CREATE TABLE users
(
    id       bigint generated by default as identity primary key,
    username text not null unique
);

CREATE TABLE comments
(
    id          bigint generated by default as identity primary key,
    user_id     bigint not null references users not null,
    content     text,
    score       bigint default 0,
    created_at  timestamp with time zone,
    post_id     bigint,
    reply_to_id bigint references comments
);



INSERT INTO users (id, username)
VALUES (1, 'amyrobson'),
       (2, 'juliusomo'),
       (3, 'ramsesmiron'),
       (4, 'maxblagun');

INSERT INTO comments (id, content, created_at, score, user_id, reply_to_id, post_id)
VALUES (1,
        'Impressive! Though it seems the drag feature could be improved. But overall it looks incredible. You''ve nailed the design and the responsiveness at various breakpoints works really well.',
        '2021-11-05', 12,
        1,
        null, 1),
       (3,
        '"If you''re still new, I''d recommend focusing on the fundamentals of HTML, CSS, and JS before considering React. It''s very tempting to jump ahead but lay a solid foundation first.',
        '2021-12-14', 4,
        3,
        2, 1),
       (4,
        'I couldn''t agree more with this. Everything moves so fast and it always seems like everyone knows the newest library/framework. But the fundamentals are what stay constant.',
        '2021-12-20', 2,
        2,
        2, 1),
       (5,
        'If you''re still new, I''d recommend focusing on the fundamentals of HTML, CSS, and JS before considering React. It''s very tempting to jump ahead but lay a solid foundation first.',
        '2021-12-14',
        4,
        3,
        4, 1),
       (2,
        'Woah, your project looks awesome! How long have you been coding for? I''m still new, but think I want to dive into React as well soon. Perhaps you can give me an insight on where I can learn React? Thanks!',
        '2021-12-10',
        5,
        4,
        null, 1),
       (6,
        'I couldn''t agree more with this. Everything moves so fast and it always seems like everyone knows the newest library/framework. But the fundamentals are what stay constant.',
        '2021-12-20',
        2,
        3,
        4, 1);
